#!/usr/bin/env python3
"""
Generated ASM Converter for CSV files
Auto-generated by ATaaS
"""

import json
from datetime import datetime

def convert_to_asm(file_content):
    """Convert CSV file to ASM format"""
    
    asm_output = {
        "$asm.manifest": "http://purl.allotrope.org/manifests/solution-analyzer/BENCHLING/2023/09/solution-analyzer.manifest",
        "measurement document": []
    }
    
    lines = file_content.strip().split('\n')
    if len(lines) < 2:
        return asm_output
    
    for i, line in enumerate(lines[1:], 1):
        values = [v.strip() for v in line.split(',')]
        if len(values) >= 2:
            measurement = {
                "measurement identifier": f"SAMPLE_{i}",
                "measurement time": datetime.utcnow().isoformat(),
                "processed data document": {
                    "value": values[1] if len(values) > 1 else "0",
                    "format": "CSV"
                }
            }
            asm_output["measurement document"].append(measurement)
    
    return asm_output

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        with open(sys.argv[1], 'r') as f:
            content = f.read()
        result = convert_to_asm(content)
        print(json.dumps(result, indent=2))
