"""
Analysis: Where does ASM information come from?
"""

import json

# Read source CSV first row
csv_line = '"11/1/2025  4:46:26 AM",,"XB21-720-0300","Default","7.183","94.5","31.4","1.80","2.38","8.21","0.25","1.02","98.7","5.68","0.43","302","1.00","","","","36.5","0.0","20.9","7.189","91.7","30.7","61.9","4.3","11.8","4.38","8.13","1:2","","25204008","25261044","25175029","25209073","","11/1/2025  4:46:26 AM","Flex2admin"'

# Read generated ASM
with open('tmp/SampleResults-1.json', 'r') as f:
    asm = json.load(f)

print("=" * 80)
print("WHERE DOES ASM INFORMATION COME FROM?")
print("=" * 80)
print()

print("1. INFORMATION DIRECTLY FROM CSV:")
print("-" * 80)
print("CSV Column: 'Sample ID' = 'XB21-720-0300'")
print("ASM Field:  sample_identifier = 'XB21-720-0300'")
print()
print("CSV Column: 'pH' = '7.183'")
print("ASM Field:  pH.value = 7.183")
print()
print("CSV Column: 'Operator' = 'Flex2admin'")
print("ASM Field:  analyst = 'Flex2admin'")
print()
print("CSV Column: 'Gln' = '1.80'")
print("ASM Field:  analyte 'glutamine' molar_concentration.value = 1.8")
print()

print("2. INFORMATION ADDED BY CONVERTER (NOT IN CSV):")
print("-" * 80)
print("CSV: <no instrument name>")
print("ASM: device_identifier = 'bioprofile flex2'")
print("     product_manufacturer = 'nova biomedical'")
print("     device_type = 'solution analyzer'")
print()
print("CSV: <no manifest>")
print("ASM: $asm.manifest = 'http://purl.allotrope.org/manifests/solution-analyzer/REC/2025/06/solution-analyzer.manifest'")
print()
print("CSV: <no measurement IDs>")
print("ASM: measurement_identifier = 'bb6dbef0-ae96-4886-8581-aa058fa9436c' (UUID generated)")
print()
print("CSV: <no converter info>")
print("ASM: ASM_converter_name = 'aws-asm-service'")
print("     ASM_converter_version = '1.0.0'")
print()

print("3. INFORMATION DERIVED/TRANSFORMED:")
print("-" * 80)
print("CSV: 'Gln' (column name)")
print("ASM: analyte_name = 'glutamine' (full chemical name)")
print()
print("CSV: 'Gln' = '1.80' (just a number)")
print("ASM: molar_concentration = {value: 1.8, unit: 'mmol/L'} (with unit)")
print()
print("CSV: 'Chemistry Dilution Ratio' = '1:2'")
print("ASM: scalar_double_datum = 0.5 (calculated: 1/2)")
print()
print("CSV: 'Date & Time' = '11/1/2025  4:46:26 AM'")
print("ASM: measurement_time = '2025-11-01T04:46:26.000+00:00' (ISO8601 format)")
print()

print("4. HOW THE SYSTEM KNEW IT WAS NOVA FLEX2:")
print("-" * 80)
print("ANSWER: It DIDN'T automatically detect it!")
print()
print("The customer told us:")
print("  - File name: 'SampleResults2025-November.csv'")
print("  - Context: Merck uses Nova BioProfile FLEX2")
print("  - We manually created 'nova_flex2_converter.py' for this specific format")
print()
print("The converter was HAND-CODED based on:")
print("  1. Customer documentation")
print("  2. Column names in the CSV (pH, PO2, Gln, etc.)")
print("  3. Knowledge of Nova FLEX2 instrument capabilities")
print("  4. ASM solution analyzer schema requirements")
print()

print("5. HARDCODED KNOWLEDGE IN THE CONVERTER:")
print("-" * 80)

knowledge = {
    "Device Info": {
        "device_identifier": "bioprofile flex2",
        "product_manufacturer": "nova biomedical",
        "device_type": "solution analyzer"
    },
    "Column Mappings": {
        "Gln": "glutamine (mmol/L)",
        "Glu": "glutamate (mmol/L)",
        "Gluc": "glucose (g/L)",
        "Lac": "lactate (g/L)",
        "NH4+": "ammonium (mmol/L)",
        "Na+": "sodium (mmol/L)",
        "K+": "potassium (mmol/L)",
        "Ca++": "calcium (mmol/L)"
    },
    "Measurement Types": {
        "pH, PO2, PCO2": "blood gas analyzer",
        "pH": "pH sensor",
        "Osm": "osmolality sensor",
        "Gln, Glu, etc": "metabolite analyzer"
    },
    "ASM Schema": "solution-analyzer/REC/2025/06"
}

for category, data in knowledge.items():
    print(f"\n{category}:")
    for key, value in data.items():
        print(f"  {key}: {value}")

print()
print("=" * 80)
print("SUMMARY:")
print("=" * 80)
print("✓ Data values (pH=7.183, Sample ID, etc.) come FROM the CSV")
print("✓ Structure, device info, units, chemical names are HARDCODED in converter")
print("✓ UUIDs, timestamps are GENERATED by converter")
print("✓ System did NOT auto-detect Nova FLEX2 - we manually created the converter")
print("=" * 80)
