"""Convert ASM Service Process Map markdown to Word document."""

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
import re


def add_styled_table(doc, headers, rows):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.style = 'Table Grid'
    table.alignment = WD_TABLE_ALIGNMENT.LEFT

    # Header row
    for i, h in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = h
        for p in cell.paragraphs:
            p.style = doc.styles['Normal']
            for run in p.runs:
                run.bold = True
                run.font.size = Pt(9)
        from docx.oxml.ns import qn
        shading = cell._element.get_or_add_tcPr()
        shading_elm = shading.makeelement(qn('w:shd'), {
            qn('w:fill'): '232F3E',
            qn('w:val'): 'clear'
        })
        shading.append(shading_elm)
        for p in cell.paragraphs:
            for run in p.runs:
                run.font.color.rgb = RGBColor(255, 255, 255)

    # Data rows
    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.rows[r_idx + 1].cells[c_idx]
            cell.text = val
            for p in cell.paragraphs:
                for run in p.runs:
                    run.font.size = Pt(9)

    return table


def build_doc():
    doc = Document()

    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(10)

    # Title
    title = doc.add_heading('ASM Transformation Service', level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle = doc.add_paragraph('End-to-End Process Map')
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.size = Pt(16)
    subtitle.runs[0].font.color.rgb = RGBColor(35, 47, 62)

    doc.add_paragraph()
    doc.add_paragraph('This document describes the complete journey of an instrument file from the moment it is generated by a laboratory instrument to the final validated, integrity-verified ASM output.')

    # --- Two Entry Points ---
    doc.add_heading('Two Entry Points', level=1)
    doc.add_paragraph('The service has two independent entry points depending on what the customer needs:')

    doc.add_heading('Entry Point 1: Convert Instrument File', level=2)
    doc.add_paragraph(
        'Use this when you have a raw instrument output file and need to produce validated ASM. '
        'This is the full pipeline (Steps 1\u20135) described in this document. '
        'Requires both an instrument file and an instrument config JSON file.'
    )

    doc.add_heading('Entry Point 2: Validate Existing ASM File (Standalone)', level=2)
    doc.add_paragraph(
        'Use this when you already have an ASM file \u2014 whether generated by your own converter, '
        'a third-party tool, or a previous conversion \u2014 and want to check if it meets Allotrope standards.'
    )
    p = doc.add_paragraph()
    p.add_run('Key point: ').bold = True
    p.add_run(
        'DVaaS validates any ASM file regardless of how it was created. '
        'It does not need the original instrument file or an instrument config. '
        'It only checks the ASM structure against Allotrope standards.'
    )

    add_styled_table(doc,
        ['Method', 'Details'],
        [
            ['Dashboard', 'Navigate to "Validate ASM File" tab, upload ASM JSON, view results, download PDF report'],
            ['API', 'POST to DVaaS endpoint with asm_data, validation_level, and generate_report flag'],
        ]
    )
    doc.add_paragraph()

    # --- Step 0 ---
    doc.add_heading('Step 0: One-Time Setup', level=1)
    doc.add_paragraph('Before converting any files, the customer completes a one-time setup per instrument.')

    add_styled_table(doc,
        ['Task', 'Who', 'How', 'Frequency'],
        [
            ['Create Instrument Config', 'Customer', 'Dashboard "Instrument Config Creator" tab', 'Once per instrument'],
            ['Register Custom Converter (if needed)', 'Customer or AWS', 'Dashboard "Converter Management" tab or API', 'Once per instrument'],
            ['Approve Custom Converter', 'Reviewer', 'Dashboard "Converter Management" tab', 'Once per converter version'],
        ]
    )
    doc.add_paragraph()
    doc.add_paragraph(
        'The Instrument Config is a JSON file containing instrument metadata: vendor, instrument type, '
        'manufacturer, model, file format, serial number, and software version. '
        'This file is reused for every conversion from that instrument. Create it once, use it forever.'
    )

    # --- Step 1 ---
    doc.add_heading('Step 1: Upload', level=1)
    doc.add_paragraph('The user provides two files:')

    add_styled_table(doc,
        ['File', 'Description', 'Example'],
        [
            ['Instrument File', 'Raw output from the instrument', 'SampleResults2025-November.csv'],
            ['Instrument Config', 'JSON metadata about the instrument', 'novabio_flex2_config.json'],
        ]
    )
    doc.add_paragraph()

    p = doc.add_paragraph()
    p.add_run('Via Dashboard: ').bold = True
    p.add_run('Navigate to "Convert Instrument File" tab, upload both files. The dashboard validates the config file in real-time.')
    p = doc.add_paragraph()
    p.add_run('Via API: ').bold = True
    p.add_run('POST to the Unified Converter endpoint with file_content, file_name, and manifest (instrument config) in the request body.')

    # --- Step 2 ---
    doc.add_heading('Step 2: Unified Converter (Intelligent Routing)', level=1)
    doc.add_paragraph(
        'The Unified Converter receives the request and determines the best conversion path. '
        'It evaluates routes in priority order and uses the first one that succeeds.'
    )

    doc.add_heading('Route Priority', level=2)
    add_styled_table(doc,
        ['Priority', 'Route', 'When It Fires', 'Field Mapping'],
        [
            ['1', 'Custom Converter Registry', 'Instrument config vendor + model match an APPROVED converter in DynamoDB', 'Required per spec (work in progress)'],
            ['2', 'Embedded Custom Converter', 'Built-in converters (e.g., Nova FLEX2) detected by file content', 'Yes \u2014 implemented for Nova FLEX2'],
            ['3', 'Allotropy Library', '31 supported instruments detected by file content patterns', 'Planned \u2014 not yet available'],
            ['4', 'ATaaS (AI-Powered)', 'All other routes failed; Bedrock Claude analyzes the file', 'Not planned'],
            ['5', 'Error', 'All routes failed', 'N/A'],
        ]
    )
    doc.add_paragraph()

    doc.add_heading('Route A: Custom Converter Registry (Highest Priority)', level=3)
    doc.add_paragraph(
        'When the instrument config provides a vendor and model that match an APPROVED converter in the registry, '
        'the Unified Converter calls the Custom Converter Service. The service loads the converter code from S3 '
        'and executes it in a sandboxed Lambda environment. Returns ASM output and field_mapping.'
    )
    doc.add_paragraph('Example instruments: Any customer-submitted converter following the Custom Converter Requirements spec.')

    doc.add_heading('Route B: Allotropy Library (Second Priority)', level=3)
    doc.add_paragraph(
        'When Route A has no matching converter, the Unified Converter calls the Multi-Instrument Service. '
        'This service uses the open-source allotropy library to parse the file using built-in instrument parsers '
        'for 31 supported instruments. Fast and rule-based.'
    )
    doc.add_paragraph(
        'Example instruments: Beckman Vi-CELL BLU/XR, Molecular Devices SoftMax Pro, PerkinElmer EnVision, '
        'Roche CEDEX BioHT, and 27 more.'
    )

    doc.add_heading('Route C: ATaaS / AI-Powered (Fallback)', level=3)
    doc.add_paragraph(
        'When Routes A and B both fail, the Unified Converter calls ATaaS. This service sends the file content '
        'to AWS Bedrock Claude 3.5 Sonnet, which analyzes the format, identifies the instrument type, and generates ASM. '
        'Also generates a standalone Python converter for future reuse. Works best for simple file formats.'
    )

    # --- Step 3 ---
    doc.add_heading('Step 3: ASM Validation (DVaaS)', level=1)
    doc.add_paragraph(
        'After conversion, the ASM output is validated by the Data Validation as a Service (DVaaS). '
        'This is the same service available standalone via Entry Point 2.'
    )

    doc.add_heading('What DVaaS Checks', level=2)
    add_styled_table(doc,
        ['Check', 'Description', 'Severity'],
        [
            ['Schema compliance', 'Does the ASM follow the Allotrope structure for this instrument type?', 'Error'],
            ['Required fields', 'Are $asm.manifest, measurement documents, sample documents present?', 'Error'],
            ['Measurement identifiers', 'Are they UUID v4 format?', 'Error'],
            ['Timestamps', 'Are they ISO 8601 with timezone?', 'Error'],
            ['Data source traceability', 'Are calculated values linked to source measurements?', 'Error'],
            ['Unit recognition', 'Are measurement units standard Allotrope units?', 'Warning'],
            ['Equipment metadata', 'Are serial number and software version present?', 'Warning'],
            ['Device control', 'Are device type and detection type specified?', 'Warning'],
        ]
    )
    doc.add_paragraph()

    doc.add_heading('Validation Levels', level=2)
    add_styled_table(doc,
        ['Level', 'Use Case', 'Strictness'],
        [
            ['Basic', 'Quick structural check', 'Low'],
            ['Comprehensive', 'Production use', 'Medium \u2014 recommended for routine use'],
            ['Certification', 'Regulatory submission', 'High \u2014 requires full equipment metadata'],
        ]
    )
    doc.add_paragraph()

    doc.add_heading('DVaaS Output', level=2)
    bullets = [
        'Validation status: VALID or INVALID',
        'Error count and details',
        'Warning count and details',
        'File metrics (technique, confidence, measurement count)',
        'PDF attestation report (downloadable)',
    ]
    for b in bullets:
        doc.add_paragraph(b, style='List Bullet')

    p = doc.add_paragraph()
    p.add_run('Important: ').bold = True
    p.add_run(
        'DVaaS validates the ASM structure. It does not compare against the source file \u2014 '
        'that is what Data Integrity Verification does (Step 4).'
    )

    # --- Step 4 ---
    doc.add_heading('Step 4: Data Integrity Verification (Work in Progress)', level=1)

    p = doc.add_paragraph()
    p.add_run('Status: ').bold = True
    p.add_run(
        'This capability is currently implemented for the Nova FLEX2 embedded converter only. '
        'It is being rolled out to all conversion routes. See the implementation status table below.'
    )
    doc.add_paragraph()

    doc.add_paragraph(
        'This step proves that every value from the source instrument file was preserved exactly in the ASM output. '
        'No rounding, no silent data loss, no transformation.'
    )

    doc.add_heading('How It Works', level=2)
    steps = [
        'The converter emits a field_mapping array during conversion.',
        'Each entry records: source field name, source value, ASM field name, ASM value, unit.',
        'The dashboard compares source_value to asm_value for every entry.',
        'Result: "100% Data Integrity Confirmed" or a list of mismatches.',
    ]
    for i, s in enumerate(steps, 1):
        doc.add_paragraph(f'{i}. {s}')

    doc.add_heading('What Gets Verified (Nova FLEX2 Example)', level=2)
    add_styled_table(doc,
        ['Category', 'Example Fields'],
        [
            ['Measurements', 'pH, PO2, PCO2, O2 Saturation, CO2 Saturation'],
            ['Metabolites', 'Glucose, Lactate, Glutamine, Glutamate, NH4+, Na+, K+, Ca++'],
            ['Calculated values', 'pH @ Temp, PO2 @ Temp, PCO2 @ Temp, HCO3'],
            ['Instrument state', 'Vessel Temperature, Vessel Pressure, Sparging O2%'],
            ['Operational data', 'Flow times, Pre-Dilution Multiplier, Dilution Ratio'],
            ['Metadata', 'Lot numbers, Vessel ID, Batch ID, Cell Type, Tray Location'],
        ]
    )
    doc.add_paragraph()

    doc.add_heading('Why This Matters for Regulatory Compliance', level=2)
    bullets = [
        'FDA 21 CFR Part 11 requires proof that electronic records are accurate and unaltered.',
        'EMA Annex 11 requires data integrity throughout the data lifecycle.',
        'An auditor can inspect the integrity report and see field-by-field proof that no data was lost or changed.',
    ]
    for b in bullets:
        doc.add_paragraph(b, style='List Bullet')

    doc.add_heading('Implementation Status', level=2)
    add_styled_table(doc,
        ['Conversion Route', 'Field Mapping', 'Status'],
        [
            ['Embedded Custom (Nova FLEX2)', 'All 40 CSV columns', 'Implemented \u2014 live today'],
            ['Custom Converter (Registry)', 'Required per spec', 'Spec complete \u2014 not yet enforced at runtime'],
            ['Allotropy Library (31 instruments)', 'Planned', 'Planned \u2014 will reuse field_mapping logic from custom converters'],
            ['ATaaS (AI)', 'Not planned', 'Not planned \u2014 AI output is best-effort'],
        ]
    )
    doc.add_paragraph()

    doc.add_heading('Rollout Plan', level=2)
    rollout = [
        'Nova FLEX2 embedded converter (done)',
        'Enforce field_mapping in Custom Converter Registry at registration time',
        'Build verification wrapper for allotropy conversions using existing field_mapping logic',
        'Evaluate feasibility for AI-generated conversions',
    ]
    for i, r in enumerate(rollout, 1):
        prefix = '\u2705 ' if i == 1 else ''
        doc.add_paragraph(f'{i}. {prefix}{r}')

    # --- Step 5 ---
    doc.add_heading('Step 5: Results', level=1)
    doc.add_paragraph('The user receives:')

    add_styled_table(doc,
        ['Output', 'Format', 'Description'],
        [
            ['ASM File', 'JSON', 'Allotrope-compliant structured data file'],
            ['Validation Report', 'PDF', 'DVaaS attestation with certificate ID, status, errors, warnings'],
            ['Integrity Report', 'Dashboard table', 'Field-by-field source-to-ASM comparison with match status'],
            ['Conversion Metadata', 'JSON', 'Conversion ID, method used, timestamp, converter version'],
        ]
    )
    doc.add_paragraph()

    p = doc.add_paragraph()
    p.add_run('Via Dashboard: ').bold = True
    p.add_run('"Download ASM File" and "Download Validation Report (PDF)" buttons. Data Integrity Verification table displayed inline.')
    p = doc.add_paragraph()
    p.add_run('Via API: ').bold = True
    p.add_run('Response includes asm_output, field_mapping, status, method, and converter_used fields.')

    # --- Converter Lifecycle ---
    doc.add_heading('Converter Lifecycle: How a New Instrument Gets Supported', level=1)

    steps = [
        ('1. Identify', 'Customer has a new instrument not currently supported. Check the Instrument Registry to confirm.'),
        ('2. Check Allotropy', 'If the instrument is one of the 31 allotropy-supported instruments, it works automatically via Route B. No custom converter needed.'),
        ('3. Build Converter', 'If not in allotropy, build a custom converter following the Custom Converter Requirements document. Must include the convert(file_content) function and field_mapping.'),
        ('4. Register', 'Submit the converter via the API or Dashboard. Status: PENDING.'),
        ('5. Review & Approve', 'A human reviewer examines the code, tests with sample files, validates ASM output, and checks field_mapping completeness. Status: APPROVED.'),
        ('6. Available', 'The converter is automatically used by the Unified Converter for any file matching that vendor + model. No further action needed.'),
    ]
    for title, desc in steps:
        p = doc.add_paragraph()
        p.add_run(title + ': ').bold = True
        p.add_run(desc)

    # --- DVaaS vs Integrity ---
    doc.add_heading('DVaaS Validation vs Data Integrity Verification', level=1)
    doc.add_paragraph('These are two complementary checks, not redundant:')

    add_styled_table(doc,
        ['', 'DVaaS Validation', 'Data Integrity Verification'],
        [
            ['Question answered', 'Is this valid ASM?', 'Is this faithful ASM?'],
            ['What it checks', 'ASM structure, schema, required fields', 'Source values preserved in ASM'],
            ['Input needed', 'ASM file only', 'Source file + ASM file (via field_mapping)'],
            ['Can catch', 'Missing fields, wrong format, broken structure', 'Dropped values, rounding, silent data loss'],
            ['Cannot catch', 'Data silently dropped during conversion', 'Structural ASM errors'],
            ['Status', 'Fully operational', 'Work in progress (Nova FLEX2 only)'],
        ]
    )
    doc.add_paragraph()
    doc.add_paragraph(
        'A converter could produce perfectly valid ASM that passes DVaaS with zero errors \u2014 '
        'but silently drop half the columns from the source file. DVaaS would never catch that '
        'because it never sees the source file. That is the gap Data Integrity Verification fills.'
    )

    # --- Live Endpoints ---
    doc.add_heading('Live Endpoints', level=1)
    add_styled_table(doc,
        ['Service', 'Endpoint', 'Purpose'],
        [
            ['Unified Converter', 'https://tqzatn5bse.execute-api.us-east-1.amazonaws.com/prod/convert', 'Single entry point for all conversions'],
            ['DVaaS', 'https://4ndgjn16zd.execute-api.us-east-1.amazonaws.com/prod/validate', 'ASM validation and certification'],
            ['Custom Converter', 'https://tfv79s08rl.execute-api.us-east-1.amazonaws.com/prod/', 'Register, approve, execute converters'],
            ['ATaaS', 'https://3dbnsq6w6h.execute-api.us-east-1.amazonaws.com/prod/convert', 'AI-powered conversion (fallback)'],
            ['Multi-Instrument', 'https://6uogqq4zb5.execute-api.us-east-1.amazonaws.com/prod/convert', 'Allotropy library (31 instruments)'],
            ['Dashboard', 'https://d2630v5zyoh8t7.cloudfront.net', 'Web UI'],
        ]
    )
    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('Recommended: ').bold = True
    p.add_run('Always use the Unified Converter endpoint. It handles routing automatically.')

    # --- Dashboard Tabs ---
    doc.add_heading('Dashboard Tabs', level=1)
    add_styled_table(doc,
        ['Tab', 'Purpose', 'When to Use'],
        [
            ['Validate ASM File', 'Validate an existing ASM file', 'You already have ASM and want to check compliance'],
            ['Convert Instrument File', 'Convert raw instrument file to ASM', 'You have a raw file and need ASM output'],
            ['Control Tower', 'Monitor conversion jobs and KPIs', 'Operational monitoring'],
            ['Instrument Config Creator', 'Create instrument config JSON files', 'One-time setup per instrument'],
            ['Instrument Registry', 'Browse supported instruments', 'Check if your instrument is supported'],
            ['Converter Management', 'Register and approve custom converters', 'Adding support for new instruments'],
        ]
    )
    doc.add_paragraph()

    # --- FAQ ---
    doc.add_heading('Frequently Asked Questions', level=1)

    faqs = [
        ('What if my instrument is already supported by allotropy but I want field_mapping?',
         'Register a custom converter for that instrument. Custom converters take priority over allotropy (Route A before Route B), and they include field_mapping for data integrity verification.'),
        ('Do I need a different instrument config for each file?',
         'No. One config per instrument. Reuse it for every file from that instrument.'),
        ('What happens if the conversion fails on all routes?',
         'The API returns an error with details about why each route failed. Typically this means the instrument needs a custom converter.'),
        ('Can I validate an ASM file without converting?',
         'Yes. This is a standalone capability. Use the "Validate ASM File" tab or call the DVaaS endpoint directly with your ASM JSON. You don\'t need the original instrument file or an instrument config.'),
        ("What's the difference between DVaaS validation and Data Integrity Verification?",
         'DVaaS checks if the ASM is structurally correct (valid schema, required fields, proper format). Data Integrity Verification checks if the ASM is faithful to the source (every value preserved exactly). Both are needed for full regulatory compliance.'),
        ('Does Data Integrity Verification work for all instruments?',
         'Not yet. It is currently implemented for the Nova FLEX2 converter. Custom converters submitted through the registry are required to include field_mapping per the requirements spec. Allotropy-based conversions do not have it yet but it is planned.'),
        ('How long does conversion take?',
         'Custom converters and allotropy: < 1 second. ATaaS (AI): 5\u201330 seconds depending on file complexity.'),
        ('Is my data stored?',
         'Files are processed in-memory only. No instrument data is persisted unless you explicitly request storage via the store_results flag.'),
    ]
    for q, a in faqs:
        p = doc.add_paragraph()
        p.add_run(f'Q: {q}').bold = True
        doc.add_paragraph(f'A: {a}')
        doc.add_paragraph()

    # --- Footer ---
    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('Built with: ').bold = True
    p.add_run('AWS Lambda, AWS Bedrock Claude, Allotropy Library, React, AWS CDK')
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    return doc


if __name__ == '__main__':
    doc = build_doc()
    output_path = 'docs/ASM-Service-Process-Map.docx'
    doc.save(output_path)
    print(f'Word document saved to {output_path}')
