import json
import requests
import os

# Read EndoScan-V XML
with open('merck/EndoScanV-Export-20230713115550.xml', 'r', encoding='utf-8') as f:
    xml_content = f.read()

print("Testing ATaaS with EndoScan-V XML")
print("=" * 60)
print(f"File size: {len(xml_content):,} bytes")
print()

# Call ATaaS
url = 'https://3dbnsq6w6h.execute-api.us-east-1.amazonaws.com/prod/convert'

response = requests.post(url, json={'file_content': xml_content}, timeout=180)
result = response.json()

print(f"Status: {response.status_code}")
print()

if response.status_code == 200:
    print("File Analysis:")
    print(json.dumps(result.get('file_analysis', {}), indent=2))
    print()
    
    # Save ASM output
    asm_output = result.get('asm_output', {})
    with open('tmp/endoscan_ataas_test.json', 'w') as f:
        json.dump(asm_output, f, indent=2)
    
    size = os.path.getsize('tmp/endoscan_ataas_test.json')
    print(f"ASM Output: {size:,} bytes")
    
    # Check manifest
    manifest = asm_output.get('$asm.manifest', asm_output.get('manifest', 'N/A'))
    print(f"Manifest: {manifest}")
    print()
    
    # Save converter code
    converter = result.get('converter_code', {})
    if converter.get('code'):
        with open('tmp/endoscan_ai_converter.py', 'w') as f:
            f.write(converter['code'])
        print(f"Converter saved: tmp/endoscan_ai_converter.py")
        print(f"Converter size: {len(converter['code']):,} characters")
        print(f"Generated by: {converter.get('generated_by', 'unknown')}")
else:
    print(f"Error: {result}")
