import json
import requests

# Test with Nova FLEX2 CSV sample
csv_content = """Sample ID,pH,Osmolality,Glucose,Lactate
SAMPLE_001,7.183,301,3.45,0.89
SAMPLE_002,7.201,298,3.52,0.91"""

url = 'https://3dbnsq6w6h.execute-api.us-east-1.amazonaws.com/prod/convert'

payload = {
    'file_content': csv_content,
    'store_results': False
}

print("Testing AI-Powered ATaaS Service...")
print("=" * 60)

try:
    response = requests.post(url, json=payload, timeout=60)
    print(f"\nStatus: {response.status_code}")
    print(f"\nRaw Response:")
    print(response.text[:500])
    
    result = response.json()
    print(f"\nFile Analysis (AI-powered):")
    print(json.dumps(result.get('file_analysis', {}), indent=2))
    
    print(f"\nASM Output (AI-generated):")
    asm = result.get('asm_output', {})
    print(f"  Manifest: {asm.get('$asm.manifest', 'N/A')}")
    print(f"  Measurements: {len(asm.get('measurement document', []))}")
    
    print(f"\nConverter Code (AI-generated):")
    converter = result.get('converter_code', {})
    print(f"  Language: {converter.get('language', 'N/A')}")
    print(f"  Filename: {converter.get('filename', 'N/A')}")
    print(f"  Generated by: {converter.get('generated_by', 'N/A')}")
    print(f"  Code length: {len(converter.get('code', ''))} characters")
    
    # Save converter code
    if converter.get('code'):
        filename = 'ai_generated_converter.py'
        with open(filename, 'w') as f:
            f.write(converter['code'])
        print(f"\n✓ Converter code saved to: {filename}")
    
    # Save full result
    with open('ataas_ai_test_result.json', 'w') as f:
        json.dump(result, f, indent=2)
    print(f"✓ Full result saved to: ataas_ai_test_result.json")
    
except Exception as e:
    print(f"Error: {e}")
