#!/usr/bin/env python3
"""
Generated ASM Converter for CSV files
Auto-generated by ATaaS
"""

import csv
import json
from datetime import datetime

def convert_to_asm(file_path):
    """Convert CSV file to ASM format"""
    
    asm_output = {
        "$asm.manifest": "http://purl.allotrope.org/manifests/solution-analyzer/BENCHLING/2023/09/solution-analyzer.manifest",
        "measurement document": []
    }
    
    with open(file_path, 'r') as f:
        reader = csv.DictReader(f)
        
        for row in reader:
            measurement = {
                "measurement identifier": row.get("Sample ID", f"SAMPLE_{datetime.now().strftime('%Y%m%d%H%M%S')}"),
                "measurement time": datetime.now().isoformat(),
                "processed data document": [{
                    "concentration": float(row.get("Concentration", 0)),
                    "pH": float(row.get("pH", 7.0)),
                    "temperature": float(row.get("Temperature", 25.0))
                }]
            }
            asm_output["measurement document"].append(measurement)
    
    return asm_output

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        result = convert_to_asm(sys.argv[1])
        print(json.dumps(result, indent=2))
