#!/usr/bin/env python3
"""
Generated ASM Converter for JSON files
Auto-generated by ATaaS
"""

import json
from datetime import datetime

def convert_to_asm(file_path):
    """Convert JSON file to ASM format"""
    
    with open(file_path, 'r') as f:
        data = json.load(f)
    
    asm_output = {
        "$asm.manifest": "http://purl.allotrope.org/manifests/plate-reader/BENCHLING/2023/09/plate-reader.manifest",
        "measurement document": []
    }
    
    measurement = {
        "measurement identifier": data.get("run_id", f"RUN_{datetime.now().strftime('%Y%m%d%H%M%S')}"),
        "measurement time": data.get("timestamp", datetime.now().isoformat()),
        "processed data document": data.get("wells", [])
    }
    
    asm_output["measurement document"].append(measurement)
    return asm_output

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        result = convert_to_asm(sys.argv[1])
        print(json.dumps(result, indent=2))
